project_id = "meal-planner"

# ---------- API ----------
[api]
enabled = true
port = 55321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[api.tls]
enabled = false

# ---------- Database ----------
[db]
port = 55322
shadow_port = 55320
major_version = 17

[db.pooler]
enabled = true
port = 55329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[db.migrations]
enabled = true
schema_paths = []

[db.seed]
enabled = false
sql_paths = []

[db.network_restrictions]
enabled = false
allowed_cidrs = ["0.0.0.0/0"]
allowed_cidrs_v6 = ["::/0"]

# ---------- Realtime ----------
[realtime]
enabled = true

# ---------- Studio ----------
[studio]
enabled = true
port = 55323
api_url = "http://127.0.0.1:55321"
openai_api_key = "env(OPENAI_API_KEY)"

# ---------- Inbucket ----------
[inbucket]
enabled = true
port = 55324

# ---------- Storage ----------
[storage]
enabled = true
file_size_limit = "50MiB"

# ---------- Auth ----------
[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000",
  "http://127.0.0.1:3000"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
enable_manual_linking = false
minimum_password_length = 6
password_requirements = ""

[auth.rate_limit]
email_sent = 2
sms_sent = 30
anonymous_users = 30
token_refresh = 150
sign_in_sign_ups = 30
token_verifications = 30
web3 = 30

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false
max_frequency = "1s"
otp_length = 6
otp_expiry = 3600

[auth.sms]
enable_signup = false
enable_confirmations = false
template = "Your code is {{ .Code }}"
max_frequency = "5s"

[auth.external.google]
enabled = true
client_id = "env(GOOGLE_OAUTH_CLIENT_ID)"
secret = "env(GOOGLE_OAUTH_CLIENT_SECRET)"
redirect_uri = "http://127.0.0.1:55321/auth/v1/callback"
url = ""

# ---------- Edge Runtime ----------
[edge_runtime]
enabled = true
policy = "oneshot"
inspector_port = 18083
deno_version = 1

# ---------- Analytics ----------
[analytics]
enabled = true
port = 55327
backend = "postgres"

# ---------- Experimental / S3 ----------
[experimental]
orioledb_version = ""
s3_host = "env(S3_HOST)"
s3_region = "env(S3_REGION)"
s3_access_key = "env(S3_ACCESS_KEY)"
s3_secret_key = "env(S3_SECRET_KEY)"
